"""Extract factual held-item tables from the qualified local Gen III source."""
import argparse,hashlib,json,re
from pathlib import Path

def build(root,output):
    paths=['include/constants/items.h','include/constants/hold_effects.h','src/data/items.h']
    raw={p:(root/p).read_bytes() for p in paths}
    definitions={k:int(v) for k,v in re.findall(r'^#define\s+(ITEM_\w+)\s+(\d+)\s*$',raw[paths[0]].decode(),re.M)}
    effects={k:int(v) for k,v in re.findall(r'^#define\s+(HOLD_EFFECT_\w+)\s+(\d+)\s*$',raw[paths[1]].decode(),re.M)}
    rows=re.findall(r'\.itemId\s*=\s*(ITEM_\w+),[\s\S]*?\.holdEffect\s*=\s*(HOLD_EFFECT_\w+),\s*\.holdEffectParam\s*=\s*(\d+)',raw[paths[2]].decode())
    if len(rows)!=375 or len(effects)!=67:raise ValueError('Unexpected native item or effect coverage.')
    items=[]
    for i,(name,effect,param) in enumerate(rows):
        if definitions.get(name) not in (0,i):raise ValueError('Native item table order mismatch: '+name)
        items.append({'id':i,'name':name,'effect':effect,'effectId':effects[effect],'param':int(param),'reserved':i!=0 and name=='ITEM_NONE'})
    data={'schema':'pokemon-suite/item-knowledge/v1','game':'firered','generation':3,'source':{'revision':'pret/pokefirered c75f352304d529f6ba92d4f74b9cf8b5c3810788','files':{p:hashlib.sha256(b).hexdigest() for p,b in raw.items()}},'effects':effects,'items':items}
    output.parent.mkdir(parents=True,exist_ok=True);output.write_text('// Generated by scripts/build-item-knowledge.py. Factual native item effects.\nexport default '+json.dumps(data,separators=(',',':'))+';\n')
    return {'items':len(items),'heldEffects':len(effects)-1}
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source',required=True,type=Path);p.add_argument('--output',required=True,type=Path);a=p.parse_args();print(json.dumps(build(a.source,a.output)))
