"""Compile offline factual move catalogs; no network calls or game prose/assets."""
import argparse,csv,hashlib,json
from pathlib import Path

def rows(root,name):
    with (root/name).open() as f:return list(csv.DictReader(f))
def build(native,pokeapi,output):
    raw=native.read_bytes();document=json.loads(raw);data=document.get('data',document)
    moves=[m for m in data['moves'] if m and m['id']>0]
    if sorted(m['id'] for m in moves)!=list(range(1,355)):raise ValueError('FireRed requires all 354 move IDs.')
    source=json.loads((pokeapi/'source.json').read_text())
    for f in source['files']:
        if hashlib.sha256((pokeapi/f['name']).read_bytes()).hexdigest()!=f['sha256']:raise ValueError('PokéAPI input changed: '+f['name'])
    reference={name:rows(pokeapi,name+'.csv') for name in ['moves','move_meta','move_meta_stat_changes','move_changelog','move_effect_changelog','move_targets','move_meta_ailments','move_meta_categories']}
    pokemon={p['identifier']:p for p in rows(pokeapi,'pokemon.csv') if p['is_default']=='1'}
    species={str(s['id']):{'name':s['name'],'weightHectograms':int(pokemon[s['name'].removeprefix('SPECIES_').lower().replace('_','-')]['weight'])}
        for s in data['species'] if s and s['name'].removeprefix('SPECIES_').lower().replace('_','-') in pokemon}
    catalog={'schema':'pokemon-suite/move-knowledge/v1','game':'firered','generation':3,
        'source':{'nativeBattleSha256':hashlib.sha256(raw).hexdigest(),'cartridgeSource':'pret/pokefirered c75f3523','pokeapi':source},
        'moves':moves,'species':species}
    output.mkdir(parents=True,exist_ok=True)
    (output/'move-catalog.js').write_text('// Generated by scripts/build-move-knowledge.py. Factual Gen III tables.\nexport default '+json.dumps(catalog,separators=(',',':'))+';\n')
    (output/'pokeapi-move-reference.json').write_text(json.dumps({'schema':'pokemon-suite/move-reference/v1','source':source,
        'semantics':'Upstream reference values and historical changes; native game rules take precedence.','tables':reference},separators=(',',':'))+'\n')
    return {'nativeMoves':len(moves),'nativeEffects':len({m['effect'] for m in moves}),'referenceMoves':len(reference['moves']),'versionChanges':len(reference['move_changelog'])}
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--native-battle',type=Path,required=True);p.add_argument('--pokeapi',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();print(json.dumps(build(a.native_battle,a.pokeapi,a.output)))
